name: Build OpenWrt Docker x86-64 image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://downloads.openwrt.org/releases/22.03.2/targets/x86/generic/openwrt-22.03.2-x86-generic-generic-ext4-rootfs.img.gz"
  #FIRMWARE_URL: "https://downloads.openwrt.org/releases/21.02.3/targets/x86/generic/openwrt-21.02.3-x86-generic-generic-ext4-rootfs.img.gz"
  #FIRMWARE_URL: "https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/openwrt-19.07.2-x86-64-generic-rootfs.tar.gz"
  REPOSITORY: tonycn/openwrt-x86
  TAG: latest

#env:
#  FIRMWARE_URL: "https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/openwrt-19.07.2-x86-64-generic-rootfs.tar.gz"
#  REPOSITORY: crazygit/openwrt-x86-64
#  TAG: 19.07.2

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
